-- MySQL Script generated by MySQL Workbench
-- Thu Jan 25 20:04:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE SCHEMA IF NOT EXISTS `grupo1` DEFAULT CHARACTER SET utf8 ;
USE `grupo1` ;

-- -----------------------------------------------------
-- Table `grupo1`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo1`.`plan` (
  `ID_PLAN` INT(11) NOT NULL,
  `NOMBREPLAN` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_PLAN`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grupo1`.`afiliado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo1`.`afiliado` (
  `NRO_AFILIADO` INT(11) NOT NULL,
  `ID_PLAN` INT(11) NOT NULL,
  `NOMBRE_COMPLETO` VARCHAR(40) NOT NULL,
  `DOCUMENTO` VARCHAR(15) NOT NULL,
  `SEXO` ENUM('M', 'F') CHARACTER SET 'big5' NOT NULL,
  `FECHA_NACIMIENTO` DATE NOT NULL,
  `DIRECCION` VARCHAR(30) NOT NULL,
  `TELEFONO` INT(11) NOT NULL,
  `MAIL` VARCHAR(20) NOT NULL,
  `ESTADO_CIVIL` ENUM('Seleccione', 'Soltero/a', 'Casado/a', 'Viudo/a', 'Concubinato', 'Divorciado/a') NOT NULL,
  `FAMILAR_A_CARGO` INT(11) NOT NULL,
  `TIPODOCU` ENUM('DNI', 'Pasaporte', 'Libreta de enrolamiento', 'Cedula de identidad') NOT NULL,
  PRIMARY KEY (`NRO_AFILIADO`),
  INDEX `FK_AFILIADO` (`ID_PLAN` ASC),
  CONSTRAINT `FK_AFILIADO`
    FOREIGN KEY (`ID_PLAN`)
    REFERENCES `pruebas`.`plan` (`ID_PLAN`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grupo1`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo1`.`localidad` (
  `ID_LOCALIDAD` INT(11) NOT NULL,
  `NOMBRE_LOC` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_LOCALIDAD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grupo1`.`practica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo1`.`practica` (
  `ID_PRACTICA` INT(11) NOT NULL,
  `NOMBREPRACTICA` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID_PRACTICA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grupo1`.`prestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo1`.`prestador` (
  `ID_PRESTADOR` INT(11) NOT NULL,
  `NOMBRE_COMPLETO` VARCHAR(40) NOT NULL,
  `ID_PRACTICA` INT(11) NOT NULL,
  `DIRECCION` VARCHAR(30) NOT NULL,
  `LOCALIDAD` INT(11) NOT NULL,
  `TELEFONO` INT(11) NOT NULL,
  PRIMARY KEY (`ID_PRESTADOR`),
  INDEX `FK_PRACTICA` (`ID_PRACTICA` ASC),
  INDEX `FK_LOCALIDAD` (`LOCALIDAD` ASC),
  CONSTRAINT `FK_LOCALIDAD`
    FOREIGN KEY (`LOCALIDAD`)
    REFERENCES `pruebas`.`localidad` (`ID_LOCALIDAD`),
  CONSTRAINT `FK_PRACTICA`
    FOREIGN KEY (`ID_PRACTICA`)
    REFERENCES `pruebas`.`practica` (`ID_PRACTICA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grupo1`.`turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo1`.`turno` (
  `ID_TURNO` INT(11) NOT NULL,
  `FECHAHORA` DATETIME NOT NULL,
  `AFILIADO` INT(11) NOT NULL,
  `PRESTADOR` INT(11) NOT NULL,
  `PRACTICA` VARCHAR(30) NOT NULL,
  `IMPORTE` FLOAT NOT NULL,
  `DURACION` INT(11) NOT NULL,
  PRIMARY KEY (`ID_TURNO`),
  INDEX `FK_PRESTADOR` (`PRESTADOR` ASC),
  CONSTRAINT `FK_PRESTADOR`
    FOREIGN KEY (`PRESTADOR`)
    REFERENCES `pruebas`.`prestador` (`ID_PRESTADOR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

